sudo: required

language: php
php:
- '7.1.9'

# services:
#   - docker

branches:
  only:
  - master

# travis runtime environment from here or settings. : https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    - ZIP_FILE="php-web-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"

    # travis-ci secure doc : https://docs.travis-ci.com/user/encryption-keys/
    # before install travis , first install ruby & gem
    # $ gem install travis
    # $ travis encrypt SOMEVAR="secretvalue"

    # AWS_ACCESS_KEY_ID_DEV
    - secure: ""
    # AWS_SECRET_ACCESS_KEY_DEV
    - secure: ""
    # AWS_ACCESS_KEY_ID_STG
    #    - secure: ""
    # AWS_SECRET_ACCESS_KEY_STG
    #    - secure: ""
    # AWS_ACCESS_KEY_ID_PROD , value : AKI....QMQ
    - secure: "aR+NfpBdPj6QeSLY4aC4PCjUr7AO9UqfDWSaQ7+cB7AsujUVt5DgmlqDpI8KxkajpO7nYEcpstcIXz5z3al7StTle3tesh06SUB3nxlLB+xftWb2EmSTtwtxyAMh3jVgfWl54THhYGho7xsSs4EL0OhLk5cPqy3Yhp1KoU1lZ3p8BhXywfoL96nJtRTDgR4kuDHc/+xYn4HVa8s5gvfobEFmWorRs0BV6ZweMo68GiOlzFfqEhtM8U+nA3umYkUmqcm28j6nY5qzmwvpRBn5i80NZw3XgtnaBA6eggpbXYv3zfwZeVGVxiuvg7CJeEMc9636Z3vO/DtRcpIEmpSComkvw61mmOarnoGde1y6eETUvIk7WiOG3c5OelAjxVB1xNj7Kbb4jkzkOpu3qkyxm4PqnMUKFv5OI8UWAec3LdWhd8gJ+c/BE67HWTxqgaf3RKp3kDH5iPIEVLI0AxwwoTFYP7hi3opF3w0a/ywJQKMpogPvYYXyS0J3eSLzu6XZtl1uzdrZFY9dCeQepoXTm3CQ6CMRs9DnG6Zo9S3udTrrNtcYPYjzLZf3HNHEDEzdAWYB8s1XMA5800AA8CQuJL3c2D9pM8uy9z7a0tpyvwhl+QYFlDrS+LaGvdjcriIFs+UqRWrVDMkideJ7RHEWKVh6D7BPs55SiqlCaFnCrcY="
    # AWS_SECRET_ACCESS_KEY_PROD
    - secure: "feUg/RkKDt0xez4wLrGLcn//Y0UGtixZ7ISKOrZ2UIce9kWufct5N5fMFPvfLF+gtVgXewEizKv+MJooM98NJ/ZunGSWWZFXyGkiDjAv9p0s4MkLVtgCrzvP+UuZZ9VA3oZ9peOmkkIIHtQJUEGE+8IyvzxSszCRTalwYEoW9cMt+wsTmeW27kBWsS8SG1RG7P+giCrqt1SuGZ4qeZSpxxAlC3NkEzDJa4AS1jS5yujCoDNq1UughKKWv3HN2YukdS6DotmOAqpZxfEWE7m+qav4TPYZv1HX5jW7ji+WQ3hV8gcKmqFxyQu8bgFRaJjL/tpsVdN/ykpG1gMyYn9EQejgMNm8PQN3Ww2V/GyefRVa4axSVV1ZRD6wKqJDUy2wsziDJf8K/P52KqqGqCgRQeYXP3cQQ/HJ3jxLuv38q6KkB7LBqbZVe9kHSro76/KLRdrrQQesxmp+Ns7lLSYU1im4dzPTgYI5rxUZWSPOZ8xZQrtbE/IVPTfNXGWiiTc4W91jeZ2fW9onkmfCckI3gL5p9Iplvt7O14XFWGsR71ySIBUGf5RzDNXIoMVHJwuTXIMUVBTlJCASYR0VMNgtSFkL42iQVjV6uzPnrZxs1IgadbMrNaUccgsXVwiVmnTJ1elPAMPOWSmQVL1/BK8WYwLdCInO/5XY1smGlomcV9o="

    # global variables
    - AWS_ACCESS_KEY_ID=''
    - AWS_SECRET_ACCESS_KEY=''
    - AWS_REGION='ap-northeast-1'
    - S3_BUCKET=''
    - S3_FOLDER='test'
    - CODEDEPLOY_APP_NAME=''
    - CODEDEPLOY_GROUP=''


# notification - https://docs.travis-ci.com/user/notifications
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: never # default: change
#     on_failure: always # default: always
# integration to slack , setup on slack travis-ci app
notifications:
  email:
    on_failure: always
    on_success: never
  # slack:
  #   secure: "nUYjAZGN+uymXquFddUgPkbD/06atgwjWBRINpn3Hgq54+iJ8mSKJ5jSUaKUV4TCaQkwwv8+8GhwGTYeTkPq6/UBGQWeIVgfhzN0iXfjjhaBu0VhWzzeLfDFbD6ok0XRYdXYVnu3G3il7iXNSbCMH8jwsnrNvZNNEDovNxMA1LmPJ5v6Gg/+kGrngxYW0lIl/0+81TEBaVKo1KeIaEirRzIlN15tTNC6t3o9zV1dXaAE2H6ZbJLYj+NpsPCPYgjUf1seMBRCrMbTKcUu9yf2jwxXqZigtdmTAW5EZGro1ESv/v2kCnMmL5bmuDRizRw7CCnAANJQdJ3jVzVGK289+S/AqdcjGMYQxFRq/iyi4T6BZIbrHOTnKWwGq18djrEFxEysL6AC1rEDg7MTw2uQpiUAFIJff3PnXLEjJbKB/DR9zn3oLij4bxJ4CdnYwxZZvQO1zhQj2GhTzOYZ/G+DW3auuQI2ufVYaAiJf9NLoYLa1XXOyChAJhV3LEnZO8x78IRxwAmQKm/K6sTBIzXZXdb/heKCibnAEYUv7ZsKf8JzIKcv0nLreARqjBoUH181O+zhcjIdJKXmloQ67lUbtOFZD6jPQ1K/W1JZoAWcjX24g1VaApYPbMJDs8hMfZNFO/s52J/UQ3zy9WWUQK6Vp1AZgqErXEqO2+3MLh/wOhI="

cache:
  directories:
  - $COMPOSER_CACHE_DIR
  - $HOME/.composer/cache




# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
  - set -e
  - echo `date +"%Y-%m-%d %H:%M:%S"`
  - echo $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH == "dev" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV;
      S3_BUCKET='';
      CODEDEPLOY_APP='';
      CODEDEPLOY_GROUP='';
    fi
  - if [[ $TRAVIS_BRANCH == "staging" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STG;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STG;
      S3_BUCKET='';
      CODEDEPLOY_APP='';
      CODEDEPLOY_GROUP='';
    fi
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD;
      S3_BUCKET='sky-104';
      CODEDEPLOY_APP='demo';
      CODEDEPLOY_GROUP='ec2';
    fi


# put testing scripts here
script:
- echo 'script step...'

before_deploy:
- cd "$TRAVIS_BUILD_DIR";
  mkdir "$TRAVIS_BUILD_DIR/zip";
  zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE" *


deploy:
- provider: S3
  access_key_id: &aws_access_key $AWS_ACCESS_KEY_ID
  secret_access_key: &aws_secret_key
    secure: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  local_dir: $TRAVIS_BUILD_DIR/zip
  bucket: $S3_BUCKET
  upload-dir: $S3_FOLDER
  skip_cleanup: true
  on:
    all_branches: true

- provider: codedeploy
  access_key_id: *aws_access_key
  secret_access_key: *aws_secret_key
  region: $AWS_REGION
  bucket: $S3_BUCKET
  key: $S3_FOLDER/$ZIP_FILE
  bundle_type: zip
  application: $CODEDEPLOY_APP
  deployment_group: $CODEDEPLOY_GROUP
  wait-until-deployed: true
  on:
    all_branches: true
